# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Jalisa
email: jalisahewitt@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome! My name is Jalisa Hewitt and I plan to lead an exciting 
 and excellent career as a programmer. You will find my resume and 
 various projects I have been working on and have completed on my website. 
 Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.codejalisa.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  codejalisa
instagram_username: lisa2lovely

# Build settings
markdown: kramdown
